"""
QuantOS — NSE trading calendar.

The single authority on whether a given date was a trading session. Nothing
else in the codebase is allowed to decide that for itself.

WHY THIS EXISTS
───────────────
Before 2026-08-18, six research scripts each carried a private copy of

    if d.weekday() < 5:   # Mon-Fri

and treated the result as "trading day". Measured against the real NSE
sessions over 2015-01-01 .. 2026-08-18, that assumption is wrong 175 times:

    naive Mon-Fri claims      3,034 days
    actual NSE sessions       2,881 days
    ├─ 164 false positives    holidays counted as trading days (5.4%)
    └─  11 false negatives    real weekend sessions dropped

The 11 dropped sessions are not exotic. They are Budget days that fell on a
weekend (2015-02-28, 2020-02-01, 2025-02-01 Sat; 2026-02-01 Sun), Muhurat
trading for Diwali (2016-10-30, 2019-10-27, 2020-11-14, 2023-11-12), and the
three 2024 disaster-recovery special live sessions (2024-01-20, 2024-03-02,
2024-05-18).

WHERE THE DATA COMES FROM
─────────────────────────
`data/nse_trading_days.txt`, one ISO date per line, generated by
`scripts/derive_nse_calendar.py`. It is *derived, not typed*: the script asks
Fyers for NIFTY 50 daily candles over a date range and takes the set of dates
that came back. A session that produced an index bar happened; one that did
not, did not.

The range form matters. The bhavcopy cache cannot serve as the source here,
even though it is local and free, because those files were fetched day-by-day
*by the buggy helper* — it never requested a Saturday, so the cache cannot
evidence a Saturday session. Asking the broker for a range instead lets the
data report days the caller never thought to ask about, which is the whole
point. Bhavcopy is used as a cross-check (see the script), not as the source.

Cross-checked at generation against 737 cached F&O bhavcopy files spanning
2023-07-24 .. 2026-07-22: every single bhavcopy date is in this calendar
(no false negatives against observed reality), and the six calendar dates with
no bhavcopy are exactly the weekend sessions the old fetcher could not have
requested.

FAIL CLOSED
───────────
The file covers a finite window. Asking about a date outside it raises
`DateOutOfRange` rather than guessing — same contract as
`core/vault/models.py`'s `Verdict.is_clear_to_proceed` and
`core/execution/slicer.py`'s refusal to trade without depth. A calendar that
silently answers "probably a Tuesday, so yes" for 2031 is worse than no
calendar, because it is wrong invisibly.

To extend the window, re-run the derivation script and commit the result.
"""

from __future__ import annotations

from bisect import bisect_left, bisect_right
from datetime import date, datetime
from functools import lru_cache
from pathlib import Path
from typing import Iterable, Union

DATA_PATH = Path(__file__).parent / "data" / "nse_trading_days.txt"

DateLike = Union[date, datetime, str]


class CalendarError(Exception):
    """Base for calendar failures."""


class DateOutOfRange(CalendarError):
    """Asked about a date the derived calendar does not cover.

    Deliberately not a "return False" — outside the window we do not know,
    and "we do not know" must not be indistinguishable from "not a session".
    """


def _coerce(d: DateLike) -> date:
    """Accept date, datetime or ISO string; always return a plain date.

    datetime is narrowed with .date(), which is correct for callers holding a
    tz-aware UTC timestamp of an Indian session only if they have already
    converted to IST. Callers working from broker candles should pass the date
    they mean, not a UTC instant near midnight.
    """
    if isinstance(d, datetime):
        return d.date()
    if isinstance(d, date):
        return d
    if isinstance(d, str):
        return date.fromisoformat(d)
    raise TypeError(f"unsupported date type: {type(d).__name__}")


@lru_cache(maxsize=1)
def _sessions() -> tuple[date, ...]:
    """The sorted tuple of every known NSE session. Cached per process."""
    if not DATA_PATH.exists():
        raise CalendarError(
            f"trading-day data missing at {DATA_PATH}. "
            "Regenerate with scripts/derive_nse_calendar.py."
        )
    days = sorted(
        date.fromisoformat(line.strip())
        for line in DATA_PATH.read_text(encoding="utf-8").splitlines()
        if line.strip()
    )
    if not days:
        raise CalendarError(f"trading-day data at {DATA_PATH} is empty.")
    return tuple(days)


@lru_cache(maxsize=1)
def _session_set() -> frozenset[date]:
    return frozenset(_sessions())


def coverage() -> tuple[date, date]:
    """(first, last) date this calendar can answer for."""
    s = _sessions()
    return s[0], s[-1]


def _require_covered(d: date) -> None:
    lo, hi = coverage()
    if not (lo <= d <= hi):
        raise DateOutOfRange(
            f"{d.isoformat()} is outside the derived calendar "
            f"({lo.isoformat()} .. {hi.isoformat()}). "
            "Re-run scripts/derive_nse_calendar.py to extend it."
        )


def is_trading_day(d: DateLike) -> bool:
    """True if NSE held a session on this date.

    Raises DateOutOfRange outside the covered window — see the module docstring
    on why this does not return False.
    """
    day = _coerce(d)
    _require_covered(day)
    return day in _session_set()


def trading_days(start: DateLike, end: DateLike) -> list[date]:
    """Every session in [start, end], inclusive of both ends.

    This is the replacement for the `_weekdays()` helpers. Note the contract
    difference that matters at call sites: those generators yielded weekends'
    worth of non-sessions and left the caller to discover there was no data.
    This yields only real sessions, so `len()` of the result is a session
    count you can divide by.
    """
    a, b = _coerce(start), _coerce(end)
    if a > b:
        raise ValueError(f"start {a} is after end {b}")
    _require_covered(a)
    _require_covered(b)
    s = _sessions()
    return list(s[bisect_left(s, a):bisect_right(s, b)])


def session_count(start: DateLike, end: DateLike) -> int:
    """Number of sessions in [start, end], inclusive."""
    return len(trading_days(start, end))


def next_trading_day(d: DateLike) -> date:
    """The first session strictly after `d`."""
    day = _coerce(d)
    _require_covered(day)
    s = _sessions()
    i = bisect_right(s, day)
    if i >= len(s):
        raise DateOutOfRange(
            f"no session after {day.isoformat()} in the derived calendar "
            f"(ends {s[-1].isoformat()}). Re-run the derivation to extend it."
        )
    return s[i]


def previous_trading_day(d: DateLike) -> date:
    """The last session strictly before `d`."""
    day = _coerce(d)
    _require_covered(day)
    s = _sessions()
    i = bisect_left(s, day)
    if i == 0:
        raise DateOutOfRange(
            f"no session before {day.isoformat()} in the derived calendar "
            f"(starts {s[0].isoformat()}). Re-run the derivation to extend it."
        )
    return s[i - 1]


def shift_sessions(d: DateLike, n: int) -> date:
    """Move `n` sessions from `d` (negative goes back).

    `d` itself need not be a session; the walk starts from where it sits in
    the ordering. n=0 returns `d` if it is a session and raises if not, since
    "zero sessions from a non-session" has no meaning worth guessing at.
    """
    day = _coerce(d)
    _require_covered(day)
    s = _sessions()
    if n == 0:
        if day not in _session_set():
            raise ValueError(
                f"{day.isoformat()} is not a session; shift_sessions(d, 0) is "
                "only defined on a session."
            )
        return day
    i = bisect_left(s, day) if n < 0 else bisect_right(s, day) - 1
    target = i + n
    if not (0 <= target < len(s)):
        lo, hi = coverage()
        raise DateOutOfRange(
            f"{n:+d} sessions from {day.isoformat()} falls outside the derived "
            f"calendar ({lo.isoformat()} .. {hi.isoformat()})."
        )
    return s[target]


def filter_sessions(dates: Iterable[DateLike]) -> list[date]:
    """Keep only the real sessions from an arbitrary iterable of dates.

    Silently drops anything outside coverage rather than raising, because the
    intended use is cleaning a caller-supplied list where out-of-range entries
    are noise. Use is_trading_day() when you need the out-of-range signal.
    """
    known = _session_set()
    return sorted({d for d in (_coerce(x) for x in dates) if d in known})
