#!/usr/bin/env python3
"""
Build an agent universe file from an NSE index constituent CSV.

NSE publishes constituent lists (ind_nifty500list.csv etc.) at
https://www.nseindia.com/products-services/indices-nifty500-index — download
the CSV by hand and run this against it. NSE rebalances semi-annually, so this
is a twice-a-year chore, not something the agent does at runtime: a static,
committed universe is what makes a Darvas track record reproducible in the
first place (a universe that moves on its own can't be backtested against).

    python scripts/build_universe.py \
        "D:/Exodus_14_14/QuantOS/ind_nifty500list.csv" \
        agent/universe_nifty500.txt --index-name "Nifty 500"

The CSV's `Symbol` column maps straight to Fyers' NSE:{symbol}-EQ form. Rows
whose Series is not EQ are dropped — the broker adapters build -EQ symbols
unconditionally, so a BE/SM series row would 404 at scan time.
"""

import argparse
import csv
import sys
from datetime import date
from pathlib import Path


def read_constituents(csv_path: Path) -> tuple[list[str], list[str]]:
    """Return (eq_symbols, skipped_non_eq). Preserves CSV order, dedupes."""
    # utf-8-sig: NSE ships these with a BOM, which would otherwise smuggle
    # itself into the first header name and break the "Symbol" lookup.
    with csv_path.open(newline="", encoding="utf-8-sig") as f:
        rows = list(csv.DictReader(f))

    if not rows or "Symbol" not in rows[0]:
        raise SystemExit(
            f"{csv_path}: no 'Symbol' column found — headers were "
            f"{list(rows[0].keys()) if rows else '(empty file)'}. "
            "Expected an NSE constituent CSV."
        )

    symbols, skipped, seen = [], [], set()
    for r in rows:
        sym = (r.get("Symbol") or "").strip().upper()
        if not sym:
            continue
        if (r.get("Series") or "").strip().upper() != "EQ":
            skipped.append(sym)
            continue
        if sym not in seen:
            seen.add(sym)
            symbols.append(sym)
    return symbols, skipped


def write_universe(symbols: list[str], out_path: Path, source: str, index_name: str) -> None:
    # ASCII-only header + explicit utf-8: this file is generated on Windows and
    # read by the agent on Linux. write_text() without an encoding uses the
    # locale default (cp1252 here), which happily encodes a character like an
    # em-dash to a byte that is not valid UTF-8 — the VM would then crash-loop
    # on UnicodeDecodeError at startup.
    header = [
        f"# {index_name} - {len(symbols)} symbols",
        f"# Generated by scripts/build_universe.py on {date.today().isoformat()}",
        f"# Source: {source}",
        "#",
        "# Do not hand-edit: regenerate from a fresh NSE CSV at each semi-annual",
        "# rebalance. Hand-curating this file is what made the old breadth reading",
        "# non-stationary (regime moved when the file was edited, not when the",
        "# market did) - see agent/main.py's regime wiring.",
        "",
    ]
    out_path.write_text("\n".join(header) + "\n".join(symbols) + "\n", encoding="utf-8")


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__,
                                 formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("csv_path", type=Path, help="NSE constituent CSV")
    ap.add_argument("out_path", type=Path, help="universe .txt to write")
    ap.add_argument("--index-name", default=None,
                    help="Label for the file header (default: derived from CSV name)")
    args = ap.parse_args()

    if not args.csv_path.exists():
        raise SystemExit(f"CSV not found: {args.csv_path}")

    symbols, skipped = read_constituents(args.csv_path)
    if not symbols:
        raise SystemExit(f"{args.csv_path}: no EQ-series symbols found.")

    index_name = args.index_name or args.csv_path.stem
    args.out_path.parent.mkdir(parents=True, exist_ok=True)
    write_universe(symbols, args.out_path, args.csv_path.name, index_name)

    print(f"Wrote {len(symbols)} symbols to {args.out_path}")
    if skipped:
        print(f"Skipped {len(skipped)} non-EQ series rows: {', '.join(skipped[:10])}"
              + (" ..." if len(skipped) > 10 else ""))
    return 0


if __name__ == "__main__":
    sys.exit(main())
